### ISSUE TITLE
PID Rt incorrect

### ISSUE THREAD

**Issue by FPWibi** [codecae/betaflight-tx-lua-revised#3]
Hello,
I found one problem in the Betaflight/PWM screen. I have a 4k PID loop frequency but the script shows 8k. When I change it to 4k in the script the betaflight configurator shows a 2k PID loop frequency.

**Comment by codecae** [comment]
is 32K enabled?

**Comment by FPWibi** [comment]
32k is OFF. I tested it on three different Quads.

**Comment by codecae** [comment]
Ok thanks :)  I will reproduce and provide an update.

**Comment by codecae** [comment]
I'm unable to reproduce this currently, but it may be due to the version of the firmware I'm using.  If the version of the firmware you are using does not automatically reboot when saving settings in that page, you may be required to reboot the flight controller manually in order for the change to be properly reflected in the configurator.  There's an update coming soon in betaflight that will enable automatic reboots when saving items on that screen.  Can you try setting the value and manually power cycle the flight controller to see if it properly updates the values in the configurator?

**Comment by codecae** [comment]
Actually -- I think I see what's happening now.  Is your gyro frequency 8k?

**Comment by FPWibi** [comment]
Yes, I use 4k for gyro and PID loop frequency.

**Comment by codecae** [comment]
I updated the master branch to include this fix.  Can you please verify?

**Comment by FPWibi** [comment]
It is working. Thank you :)

**Comment by PrestonHack** [comment]
I experienced this but in my test I think it was only because I had the configurator connected while using the script. When disconnected from the configurator this did not happen.
